Return contractAdress permit in getContext
stakeordie/griptape.js pull request #180
Opened 2022-04-06 00:06 UTC by VPringle97

issue #179 done.

2022-04-08 18:16 UTC, luiseel requested changes

2022-04-08 18:16 UTC, luiseel commented on src/contracts/index.ts
> +import { permitManager } from '..';
Specify the file please

2022-04-08 18:29 UTC, gildardoSOD commented on src/contracts/index.ts
> +  let permitData = account?.permits.find(
Done

2022-04-08 18:29 UTC, gildardoSOD commented on src/contracts/index.ts
> +import { permitManager } from '..';
Done

2022-04-11 16:54 UTC, luiseel approved these changes

2022-04-11 16:54 UTC, merged